version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka_101:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 101 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka_101
  kafka_102:
    build: .
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 102
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka_102
  kafka_103:
    build: .
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 103
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka_103
